### ISSUE TITLE
gppt needs to be fixed

### ISSUE THREAD

**Issue by MGMCN** [MGMCN/pppixiv#71]
```bash
2023-09-02 13:38:54 [2023-09-02 04:38:54,754] DEBUG in main: =====================================================================================
2023-09-02 13:38:54 [2023-09-02 04:38:54,754] DEBUG in main: Authorized on pixiv account gaoshancq@qq.com. Please wait for authentication.
2023-09-02 13:39:15 Traceback (most recent call last):
2023-09-02 13:39:15   File "/APP/main.py", line 26, in <module>
2023-09-02 13:39:15     success, msg = app.run_services()
2023-09-02 13:39:15                    ^^^^^^^^^^^^^^^^^^
2023-09-02 13:39:15   File "/APP/app.py", line 21, in run_services
2023-09-02 13:39:15     success, msg = self.myPixiv.start_pixiv_session()
2023-09-02 13:39:15                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-02 13:39:15   File "/APP/services/pixiv.py", line 225, in start_pixiv_session
2023-09-02 13:39:15     success = self.get_token()
2023-09-02 13:39:15               ^^^^^^^^^^^^^^^^
2023-09-02 13:39:15   File "/APP/services/pixiv.py", line 54, in get_token
2023-09-02 13:39:15     res = self.pixivTokenApi.login(headless=True, username=self.pixivUsername, password=self.pixivPassword)
2023-09-02 13:39:15           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-02 13:39:15   File "/usr/lib/python3.11/site-packages/gppt/_selenium.py", line 93, in login
2023-09-02 13:39:15     self.__try_login()
2023-09-02 13:39:15   File "/usr/lib/python3.11/site-packages/gppt/_selenium.py", line 163, in __try_login
2023-09-02 13:39:15     el = self.driver.find_element(
2023-09-02 13:39:15          ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-02 13:39:15   File "/usr/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
2023-09-02 13:39:15     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
2023-09-02 13:39:15            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-02 13:39:15   File "/usr/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
2023-09-02 13:39:15     self.error_handler.check_response(response)
2023-09-02 13:39:15   File "/usr/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
2023-09-02 13:39:15     raise exception_class(message, screen, stacktrace)
2023-09-02 13:39:15 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@type='submit'][contains(text(), 'ログイン') or contains(text(), 'Login') or contains(text(), '登录') or contains(text(), '로그인') or contains(text(), '登入')]"}
```

**Comment by MGMCN** [comment]
Your solution before gppt was fixed was to manually edit your login token within the code.

**Comment by MGMCN** [comment]
It's recommended to run it locally, not within docker, and you won't have the problem above.
